name: commit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  committed:
    name: conventional commits (committed)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: crate-ci/committed@master
        with:
          args: "-vv --no-merge-commit --no-fixup"
          commits: ${{ github.event_name == 'pull_request' && format('{0}..{1}', github.event.pull_request.base.sha, github.event.pull_request.head.sha) || 'HEAD~1..HEAD' }}
